CodecoolShop/Codecool.CodecooShop/Models/Cart.cs
using System.Collections.Generic;
using System.Linq;

namespace Codecool.CodecoolShop.Models;

public class Cart : BaseModel
{
    public Cart()
    {
        Products = new Dictionary<Product, int>();
    }

    public Dictionary<Product, int> Products { get; set; }

    private bool IsProductInCart(Product product)
    {
        var results = Products.Where(p => p.Key.Id == product.Id).Select(p => p.Key);
        if (results.Any()) return true;

        return false;
    }

    public void AddProduct(Product product)
    {
        if (IsProductInCart(product))
        {
            product.CartQuantity += 1;
            Products[product] += 1;
        }
        else
        {
            product.IsInCart = true;
            product.CartQuantity = 1;
            Products.Add(product, 1);
        }
    }

    public void MinusProduct(Product product)
    {
        if (IsProductInCart(product))
        {
            if (Products[product] == 1)
            {
                product.CartQuantity = 0;
                product.IsInCart = false;
                Products.Remove(product);
            }
            else
            {
                product.CartQuantity -= 1;
                Products[product] -= 1;
            }
        }
    }

    public void DeleteProduct(Product product)
    {
        if (IsProductInCart(product))
        {
            product.CartQuantity = 0;
            product.IsInCart = false;
            Products.Remove(product);
        }
    }

    public int TotalProducts()
    {
        return Products.Sum(p => p.Value);
    }

    public int TotalPrice()
    {
        return (int) Products.Sum(p => p.Key.DefaultPrice * p.Value);
    }
}

CodecoolShop/Codecool.CodecooShop/Controllers/AddressController.cs
using System;
using System.Linq;
using Codecool.CodecoolShop.Areas.Identity.Data;
using Data;
using Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Codecool.CodecoolShop.Controllers;

public class AddressController : Controller
{
    private readonly CodecoolShopContext _context;
    private readonly ILogger<AddressController> _logger;
    private readonly UserManager<CodecoolCodecoolShopUser> _userManager;

    public AddressController(ILogger<AddressController> logger, CodecoolShopContext context,
        UserManager<CodecoolCodecoolShopUser> userManager)
    {
        _logger = logger;
        _context = context;
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        if (User.Identity.IsAuthenticated && CartIsNotEmpty())
        {
            _logger.LogInformation($"Address page viewed on {DateTime.Now}");
            return View();
        }

        _logger.LogInformation($"Address page tried to view on {DateTime.Now}");
        return RedirectToAction("Index", "Product");
    }

    [HttpPost]
    [AcceptVerbs]
    public IActionResult Index(Address addressGet)
    {
        _logger.LogInformation($"{DateTime.Now} Action Controller HttpPost executed");
        if (User.Identity.IsAuthenticated)
        {
            _logger.LogInformation($"{DateTime.Now} User Identity Authenticated.");
            if (!ModelState.IsValid)
            {
                _logger.LogInformation($" {DateTime.Now} Modelstate in address is not valid.");
                return View();
            }

            if (User.Identity.IsAuthenticated && CartIsNotEmpty())
            {
                _logger.LogInformation(
                    $" {DateTime.Now} adding address information into DB. Cart verified/ is not empty.");
                var userId = _userManager.GetUserId(User);
                var addressId = _context.Orders.Where(o => o.User_id == userId && o.OrderPayed == "No")
                    .Select(o => o.Address.Id).First();
                var address = _context.Addresses.First(a => a.Id == addressId);
                address.Phone = addressGet.Phone;
                address.City = addressGet.City;
                address.Country = addressGet.Country;
                address.Email = addressGet.Email;
                address.FullName = addressGet.FullName;
                address.Street = addressGet.Street;
                address.Zip = addressGet.Zip;
                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Payment");
        }

        return RedirectToAction("Index", "Product");
    }

    public IActionResult Submit(IFormCollection collection)
    {
        _logger.LogInformation($"{DateTime.Now} User pressed submit on Address page.");
        return View("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        _logger.LogInformation($"Error on: {DateTime.Now}");
        return RedirectToAction("Index", "Product");
    }

    private bool CartIsNotEmpty()
    {
        var userId = _userManager.GetUserId(User);
        var cart = _context.OrderedProducts
            .Include(p => p.Order)
            .Any(p => p.Order.User_id == userId && p.Order.OrderPayed == "No");

        return cart;
    }
}

CodecoolShop/Codecool.CodecooShop/Controllers/CartController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Codecool.CodecoolShop.Areas.Identity.Data;
using Codecool.CodecoolShop.Models;
using Data;
using Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Address = Domain.Address;
using Order = Domain.Order;
using PaymentInfo = Domain.PaymentInfo;

namespace Codecool.CodecoolShop.Controllers;

public class OrderHisotryModel
{
    public List<Order> order;
    public List<OrderedProduct> products { get; set; }
}

public class CartController : Controller
{
    private readonly CodecoolShopContext _context;
    private readonly ILogger<CartController> _logger;
    private readonly UserManager<CodecoolCodecoolShopUser> _userManager;

    public CartController(ILogger<CartController> logger, CodecoolShopContext context,
        UserManager<CodecoolCodecoolShopUser> userManager)
    {
        _logger = logger;
        _context = context;
        _userManager = userManager;
    }

    public IActionResult Index()
    {
        List<OrderedProduct> orderedProducts = null;
        if (User.Identity.IsAuthenticated)
        {
            var userId = _userManager.GetUserId(User);
            orderedProducts = _context.OrderedProducts
                .Include(p => p.Order)
                .Where(p => p.Order.User_id == userId && p.Order.OrderPayed == "No")
                .ToList();
            return View(orderedProducts);
        }

        return RedirectToAction("Index", "Product");
    }

    public IActionResult OrderHistory()
    {
        if (User.Identity.IsAuthenticated)
        {
            var userId = _userManager.GetUserId(User);
            var orderedProducts = _context.OrderedProducts
                .Include(p => p.Order)
                .Where(p => p.Order.User_id == userId && p.Order.OrderPayed == "Yes")
                .ToList();
            var order = _context.Orders
                .Include(o => o.Address)
                .Include(o => o.PaymentInfo)
                .Where(o => o.User_id == userId && o.OrderPayed == "Yes").ToList();
            var model = new OrderHisotryModel
            {
                order = order,
                products = orderedProducts
            };
            return View(model);
        }

        return RedirectToAction("Index", "Product");
    }

    public IActionResult Add(int? id)
    {
        if (User.Identity.IsAuthenticated)
        {
            if (ProductAlreadyInCart(id))
                IncreaseProductQuantity(id);
            else
                AddNewProductToCart(id);
        }

        return RedirectToAction("Index");
    }

    private void IncreaseProductQuantity(int? id)
    {
        var product = _context.OrderedProducts.Include(p => p.Order)
            .First(p => p.ProductId == id && p.Order.OrderPayed == "No");
        product.Quantity++;
        _context.SaveChanges();
    }

    private void AddNewProductToCart(int? id)
    {
        var userId = _userManager.GetUserId(User);
        var product = _context.Products.Where(p => p.Id == id).First();
        Order order = null;
        if (!UserHasOrder(userId))
        {
            var address = new Address
            {
                City = "",
                Country = "",
                Email = "",
                FullName = "",
                Phone = "",
                Street = "",
                Zip = ""
            };
            var payment = new PaymentInfo
            {
                NameOnCard = "",
                CardNumber = "",
                CVV = "",
                ExpMonth = "",
                ExpYear = ""
            };
            order = new Order {Address = address, User_id = userId, PaymentInfo = payment, OrderPayed = "No"};
            _context.Addresses.Add(address);
            _context.Orders.Add(order);
        }

        if (UserHasOrder(userId)) order = _context.Orders.First(o => o.User_id == userId && o.OrderPayed == "No");

        var orderedProduct = new OrderedProduct
        {
            Currency = product.Currency,
            Name = product.Name,
            Price = product.DefaultPrice,
            Order = order,
            ProductId = product.Id,
            Quantity = 1
        };
        _context.OrderedProducts.Add(orderedProduct);
        _context.SaveChanges();
    }

    private bool UserHasOrder(string userId)
    {
        return _context.Orders.Any(o => o.User_id == userId && o.OrderPayed == "No");
    }

    private bool ProductAlreadyInCart(int? id)
    {
        var userId = _userManager.GetUserId(User);
        return _context.OrderedProducts
            .Include(p => p.Order)
            .Any(p => p.ProductId == id && p.Order.User_id == userId && p.Order.OrderPayed == "No");
    }

    public IActionResult Minus(int? id)
    {
        if (User.Identity.IsAuthenticated)
            if (ProductAlreadyInCart(id))
                DecreaseProductQuantity(id);

        return RedirectToAction("Index");
    }

    private void DecreaseProductQuantity(int? id)
    {
        var product = _context.OrderedProducts.Include(p => p.Order)
            .First(p => p.ProductId == id && p.Order.OrderPayed == "No");
        product.Quantity--;
        if (product.Quantity == 0)
            _context.OrderedProducts.Remove(product);
        _context.SaveChanges();
    }

    public IActionResult Delete(int? id)
    {
        if (User.Identity.IsAuthenticated)
            if (ProductAlreadyInCart(id))
            {
                var userId = _userManager.GetUserId(User);
                var product = _context.OrderedProducts
                    .Include(p => p.Order)
                    .First(p => p.ProductId == id && p.Order.User_id == userId && p.Order.OrderPayed == "No");
                _context.OrderedProducts.Remove(product);
                _context.SaveChanges();
            }

        return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

CodecoolShop/Codecool.CodecooShop/Views/Cart/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Domain.OrderedProduct>

<div class="container">

    @if (Model.Count == 0)
    {
        <h1>Your cart is empty.</h1>
    }
    @if (Model.Count > 0)
    {
        @foreach (var element in Model)
        {
            <div style="display: flex;">
                <img src="img/@(element.Name).jpg" style="height: 50px; margin-top: 15px; width: 50px;">

                <div style="height: 40px; margin-top: 20px; padding-left: 20px;">
                    <a asp-action="Add" asp-route-id="@element.ProductId" style="border-radius: 20px; color: black; font-size: 25px; text-decoration: none; width: 40px;">
                        <i class="bi bi-plus-circle"></i>
                    </a>
                    <a asp-action="Minus" asp-route-id="@element.ProductId" style="border-radius: 20px; color: black; font-size: 25px; text-decoration: none; width: 40px;">
                        <i class="bi bi-dash-circle"></i>
                    </a>
                    <a asp-action="Delete" asp-route-id="@element.ProductId" style="border-radius: 20px; color: red; font-size: 25px; text-decoration: none; width: 40px;">
                        <i class="bi bi-x-circle-fill"></i>
                    </a>
                </div>

                <div style="padding-left: 20px;">
                    <p>@element.Name</p>
                    <p style="margin-top: -15px;">Price: @element.Price @element.Currency</p>
                    <p style="margin-top: -15px;">Quantity: @element.Quantity</p>
                </div>
            </div>
            <hr/>
        }
        <div>
            <b>Total products:</b> @Model.Sum(p => p.Quantity)
            <br/>
            <b>Total price:</b> @Model.Sum(p => p.Price * p.Quantity) @Model[0].Currency
            <br/>
            <a asp-action="Index" asp-controller="Address" type="button" class="btn btn-primary">Go to checkout</a>
        </div>
    }
</div>

CodecoolShop/Codecool.CodecooShop/Views/Cart/OrderHistory.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model Codecool.CodecoolShop.Controllers.OrderHisotryModel

<div class="container">

    @if (Model.order.Count == 0)
    {
        <h1>Your order history is empty.</h1>
    }
    @if (Model.order.Count > 0)
    {
        @foreach (var order in Model.order)
        {
            <div style="border: 1px solid gray; margin-bottom: 20px; padding: 10px;">
                <p>Order @order.Id</p>
                <p>Biling Info</p>
                <p>@order.Address.FullName</p>
                <p>@order.Address.Email</p>
                <p>@order.Address.Phone</p>
                <p>@order.Address.Street</p>
                <p>@order.Address.City @order.Address.Zip</p>
                <p>@order.Address.Country</p>
                <hr/>
                @foreach (var element in Model.products.Where(p => p.Order.Id == order.Id))
                {
                    <div style="display: flex;">
                        <img src="/img/@(element.Name).jpg" style="height: 50px; margin-top: 15px; width: 50px;">

                        <div style="padding-left: 20px;">
                            <p>@element.Name</p>
                            <p style="margin-top: -15px;">Price: @element.Price @element.Currency</p>
                            <p style="margin-top: -15px;">Quantity: @element.Quantity</p>
                        </div>
                    </div>
                    <hr/>
                }
                <div>
                    <b>Total products:</b> @Model.products.Where(p => p.Order.Id == order.Id).Sum(p => p.Quantity)
                    <br/>
                    <b>Total price:</b> @Model.products.Where(p => p.Order.Id == order.Id).Sum(p => p.Quantity * p.Price) @Model.products[0].Currency
                    <br/>
                </div>
            </div>
        }
    }
</div>